add testing for pylint and pytest scores

diff --git a/.github/workflows/pytest_and_pylint.yml b/.github/workflows/pytest_and_pylint.yml
--- a/.github/workflows/pytest_and_pylint.yml
+++ b/.github/workflows/pytest_and_pylint.yml
@@ -98,7 +98,17 @@ jobs:
       - name: Check Pylint Score and all tests pass
         if: '!cancelled()'
         run: |
-          (( env.PASSED_PERCENTAGE -eq 100 )) && (( env.AVG_SCORE -eq 10.00 ))
+          if [[ $env.PASSED_PERCENTAGE -eq 100 ]]; then
+            echo "All tests passed!"
+          else
+            echo "Some tests failed!"
+            exit 1
+          fi
+          fi [[ $(bc <<< "scale=2; $env.AVG_SCORE == 10.00") ]]; then
+            echo "Pylint score is perfect"
+          else
+            echo "Pylint score is not 10.00."
+          fi
       
 
       # Generate the badge for passed_percentage
